"use client";
/* eslint-disable @typescript-eslint/no-explicit-any, react-hooks/set-state-in-effect */

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { Activity, ArrowDown, ArrowRight, Check, Database, Gauge, Globe2, Layers3, Menu, Network, RefreshCw, Search, Send, ShieldCheck, Siren, Sparkles, X, Zap } from "lucide-react";

export type SarathiView = "home"|"command"|"intelligence"|"warnings"|"agents"|"agent"|"sitrep"|"sitrep-detail"|"alerts"|"ask"|"sources"|"system"|"event";
const nav = [["Home","/"],["Command","/command"],["Intelligence","/intelligence"],["Warnings","/warnings"],["Agents","/agents"],["SITREP","/sitrep"],["Alerts","/alerts"],["Ask","/ask"]] as const;

function useLiveData(endpoint:string){
  const [data,setData]=useState<any>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const response=await fetch(endpoint,{cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json.message||`Request failed (${response.status})`);setData(json)}catch(error){setError(error instanceof Error?error.message:"Live data is unavailable.")}finally{setLoading(false)}},[endpoint]);
  useEffect(()=>{load()},[load]); return {data,loading,error,reload:load};
}

export function SarathiApp({view,detail}:{view:SarathiView;detail?:string}){
  const pathname=usePathname();const[menuOpen,setMenuOpen]=useState(false);
  useEffect(()=>setMenuOpen(false),[pathname]);
  return <main className="sarathi-root">
    <header className="global-nav">
      <Link href="/" className="wordmark"><span className="wordmark-glyph"><Zap/></span><span><b>SARATHI</b><small>Disaster Intelligence</small></span></Link>
      <nav className={menuOpen?"nav-links open":"nav-links"} aria-label="Primary navigation">{nav.map(([label,href])=><Link key={href} href={href} className={pathname===href||(href!=="/"&&pathname.startsWith(href))?"active":""}>{label}</Link>)}</nav>
      <Link href="/system" className="system-live"><span className="live-dot"/> SYSTEM STATUS <ArrowRight/></Link>
      <button className="mobile-menu" aria-label="Toggle navigation" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button>
    </header>
    <div className="route-frame">
      {view==="home"&&<Home/>}{view==="command"&&<CommandCenter/>}{view==="intelligence"&&<Intelligence/>}{view==="warnings"&&<Warnings alerts={false}/>} {view==="alerts"&&<Warnings alerts/>}
      {view==="agents"&&<Agents/>}{view==="agent"&&<AgentDetail slug={detail}/>} {view==="sitrep"&&<Sitrep/>}{view==="sitrep-detail"&&<Sitrep/>}
      {view==="ask"&&<Ask/>}{view==="sources"&&<Sources/>}{view==="system"&&<System/>}{view==="event"&&<Intelligence/>}
    </div>
    {view!=="home"&&<footer className="utility-nav"><Link href="/sources"><Database/> Sources</Link><Link href="/system"><Activity/> System health</Link><span>Live public-data workspace</span></footer>}
  </main>
}

function Home(){return <div className="home-page">
  <section className="home-hero">
    <div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/>
    <p className="eyebrow reveal-up">MULTI-AGENT DISASTER INTELLIGENCE</p>
    <h1 className="reveal-up delay-one">Clarity when every<br/><em>second matters.</em></h1>
    <p className="hero-copy reveal-up delay-two">Sarathi turns live weather, natural-event and seismic feeds into one operational picture—then coordinates specialized agents to explain what changed and what deserves attention.</p>
    <div className="hero-actions reveal-up delay-three"><Link href="/command" className="cta-primary">Open command center <ArrowRight/></Link><Link href="#how-it-works" className="cta-quiet">See how it works <ArrowDown/></Link></div>
    <div className="hero-console float-in"><div className="console-top"><span><i/> LIVE OPERATIONS</span><b>SARATHI / COMMAND</b><span>API CONNECTED</span></div><div className="console-map"><MapScene/><div className="pulse-core"><span/><i/></div><div className="console-card card-a"><small>01 / INGEST</small><b>Public data feeds</b><p>Weather · Events · Seismic</p></div><div className="console-card card-b"><small>02 / REASON</small><b>Selective agents</b><p>Parallel, source-attributed analysis</p></div><div className="console-card card-c"><small>03 / ACT</small><b>Human-reviewed alerts</b><p>SITREPs · Warnings · Guidance</p></div></div></div>
    <a href="#mission" className="scroll-cue">SCROLL TO EXPLORE <ArrowDown/></a>
  </section>
  <section className="mission-section" id="mission"><div className="section-kicker">01 / THE MISSION</div><div><h2>One shared picture.<br/>Many expert agents.</h2><p>Disaster response data arrives fragmented and fast. Sarathi’s central orchestrator activates only the capabilities a situation needs, runs them in parallel, and carries source evidence into every result.</p></div></section>
  <section className="feature-marquee" aria-label="Core capabilities"><span>EARLY WARNING</span><i/> <span>LIVE INTELLIGENCE</span><i/> <span>VERIFIED SOURCES</span><i/> <span>PUBLIC GUIDANCE</span></section>
  <section className="process-section" id="how-it-works"><div className="section-kicker">02 / HOW IT WORKS</div><h2>From signal to decision.</h2><div className="process-grid">{[
    ["01","Observe","Open-Meteo, NASA EONET and USGS provide fresh machine-readable signals.",Globe2],
    ["02","Coordinate","The central agent routes the request to weather, event, seismic and risk capabilities.",Network],
    ["03","Verify","Every operational value keeps its source, freshness and availability state.",ShieldCheck],
    ["04","Respond","Teams receive a shared command view, current SITREP and reviewable warnings.",Siren]
  ].map(([n,title,copy,Icon]:any)=><article key={n}><span>{n}</span><Icon/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="principles"><article><p className="section-kicker">03 / BUILT FOR TRUST</p><h2>No quiet fabrication.</h2></article><article><h3>Unavailable means unavailable.</h3><p>If a provider fails, Sarathi shows a clear fallback message and source health instead of substituting invented incident values.</p></article><article><h3>People stay in control.</h3><p>High-impact public alerts stay reviewable. Source links and calculation bases remain visible to operators.</p></article></section>
  <section className="home-final"><Sparkles/><h2>See the live operational picture.</h2><p>Open the command center to inspect current API data for Chennai and global natural hazards.</p><Link href="/command" className="cta-primary">Launch Sarathi <ArrowRight/></Link></section>
</div>}

function PageHeading({index,title,subtitle,onRefresh}:{index:string;title:string;subtitle:string;onRefresh?:()=>void}){return <div className="page-heading"><div className="heading-index">{index}</div><div><h1>{title}</h1><p>{subtitle}</p></div>{onRefresh&&<button className="refresh-button" onClick={onRefresh}><RefreshCw/> Refresh live data</button>}</div>}
function Loading(){return <div className="state-card loading-state"><RefreshCw/><h2>Connecting to live sources</h2><p>Sarathi is requesting current public data.</p></div>}
function Fallback({message,reload}:{message?:string;reload:()=>void}){return <div className="state-card error-state"><Activity/><h2>Live data unavailable</h2><p>{message||"The connected providers did not respond. No substitute values are being shown."}</p><button onClick={reload}><RefreshCw/> Try again</button></div>}
function Freshness({time}:{time?:string}){return time?<span className="freshness"><span className="live-dot"/> Updated {new Date(time).toLocaleString()}</span>:null}

function CommandCenter(){const{data,loading,error,reload}=useLiveData("/api/dashboard");if(loading)return <Page><PageHeading index="01" title="Command" subtitle="Live overview of the situation"/><Loading/></Page>;if(error||!data||data.status==="unavailable")return <Page><PageHeading index="01" title="Command" subtitle="Live overview of the situation"/><Fallback message={error||data?.message} reload={reload}/></Page>;const w=data.weather,r=data.risk;return <Page><PageHeading index="01" title="Command" subtitle="Live overview of the situation" onRefresh={reload}/><Freshness time={data.fetchedAt}/><section className="command-map"><MapScene/><div className="map-title"><span>Situation,</span> {data.location.name}<small>Live public-data view</small></div><article className="float-panel threat-panel"><p>Weather risk</p><div className="big-risk">{r?.score??"—"} <Badge tone={tone(r?.severity)}>{r?.severity??"UNKNOWN"}</Badge></div><h3>Calculated conditions</h3><small>{r?.basis}</small></article><article className="float-panel intel-panel"><p>Global intelligence</p><strong className="big-number">{data.events.length+data.earthquakes.length}</strong><span>Current API events</span></article><article className="float-panel weather-panel"><p>Open-Meteo <LiveStatus/></p><strong className="big-number blue">{w?.rain24h}<em> mm</em></strong><span>Precipitation / 24h</span><b className="confidence">{w?.temperature}°<small>Temperature</small></b></article><article className="float-panel risk-panel"><p>Next 24 hours</p><strong className="big-number blue">{w?.rainNext24h}<em> mm</em></strong><span>{w?.maxRainProbability}% peak probability</span></article><div className="event-callout"><span className={`hazard-dot ${tone(r?.severity)}`}/><div><b>{r?.severity} weather risk</b><small>{data.location.name}</small></div><Link href="/warnings"><ArrowRight/></Link></div></section><SourceStrip sources={data.sources}/></Page>}

function Intelligence(){const{data,loading,error,reload}=useLiveData("/api/intelligence");const[selected,setSelected]=useState<any>(null);if(loading)return <Page><PageHeading index="02" title="Intelligence" subtitle="Multi-source natural hazard awareness"/><Loading/></Page>;if(error||!data||data.status==="unavailable")return <Page><PageHeading index="02" title="Intelligence" subtitle="Multi-source natural hazard awareness"/><Fallback message={error||data?.message} reload={reload}/></Page>;const items=data.items||[];return <Page><PageHeading index="02" title="Intelligence" subtitle="NASA EONET and USGS live event feeds" onRefresh={reload}/><Freshness time={data.fetchedAt}/><section className="intel-board"><div className="intel-map"><MapScene/><div className="search-map"><Search/> Global event overview</div><div className="map-counter"><Globe2/><b>{items.length}</b><span>current events</span></div></div><aside className="intel-side"><h2>Source health</h2><SourceStrip sources={data.sources}/></aside></section>{items.length?<div className="stream-section"><h2>Current intelligence</h2>{items.map((item:any)=><button key={item.id} className={selected?.id===item.id?"stream-row active":"stream-row"} onClick={()=>setSelected(item)}><time>{item.date||item.time?new Date(item.date||item.time).toLocaleDateString():"Current"}</time><span className="stream-type">{item.category||`M${item.magnitude??"—"}`}</span><div><b>{item.title}</b><small>{item.source}</small></div><strong>{item.magnitude!=null?`Magnitude ${item.magnitude}`:"Open event"}</strong><Badge tone="green">LIVE API</Badge><a href={item.link||"#"} target="_blank" rel="noreferrer" onClick={e=>{if(!item.link)e.preventDefault()}}>Source ↗</a></button>)}</div>:<Empty title="No current events returned" copy="The providers responded successfully but returned no matching open events."/>}</Page>}

function Warnings({alerts}:{alerts:boolean}){const{data,loading,error,reload}=useLiveData(alerts?"/api/alerts":"/api/warnings");const[reviewed,setReviewed]=useState(false);if(loading)return <Page><PageHeading index={alerts?"07":"03"} title={alerts?"Alerts":"Warnings"} subtitle="Threshold-based live conditions"/><Loading/></Page>;if(error||!data||data.status==="unavailable")return <Page><PageHeading index={alerts?"07":"03"} title={alerts?"Alerts":"Warnings"} subtitle="Threshold-based live conditions"/><Fallback message={error||data?.message} reload={reload}/></Page>;const items=alerts?data.alerts:data.warnings;return <Page><PageHeading index={alerts?"07":"03"} title={alerts?"Alert Center":"Warnings"} subtitle={alerts?"Human-reviewed public warning workflow":"Current calculated risk signals"} onRefresh={reload}/><Freshness time={data.fetchedAt}/>{items?.length?<section className="warning-detail solo"><header><div><h2>{items[0].title}</h2><p>{items[0].place}</p></div><Badge tone={tone(items[0].severity)}>{items[0].severity}</Badge></header><div className="warning-map"><MapScene/><div className="danger-ring"/></div><div className="warning-metrics"><Metric label="Risk score" value={String(items[0].score)}/><Metric label="Observed at" value={new Date(items[0].time).toLocaleTimeString()}/><Metric label="Data status" value="LIVE"/></div>{alerts&&<div className="approval-strip"><ShieldCheck/><p><b>{reviewed?"Marked for operator review":"Human approval required"}</b><br/>Public distribution requires an authorized operator.</p><button onClick={()=>setReviewed(true)} disabled={reviewed}>{reviewed?<><Check/> Queued</>:"Review alert"}</button></div>}</section>:<Empty title="No active warning threshold" copy="Live sources responded, and the current risk score is below the warning threshold."/>}</Page>}

function Agents(){const{data,loading,error,reload}=useLiveData("/api/agents");if(loading)return <Page><PageHeading index="04" title="Agents" subtitle="Selective multi-agent intelligence"/><Loading/></Page>;if(error||!data)return <Page><PageHeading index="04" title="Agents" subtitle="Selective multi-agent intelligence"/><Fallback message={error||data?.message} reload={reload}/></Page>;return <Page><PageHeading index="04" title="Agents" subtitle="Capabilities backed by connected public APIs" onRefresh={reload}/><Freshness time={data.fetchedAt}/><section className="agent-network"><div className="orchestrator-node"><span>S</span><div><small>CENTRAL AGENT</small><b>Sarathi Orchestrator</b><p>Routes tasks only to relevant capabilities</p></div><LiveStatus/></div><div className="network-lines"/><div className="agent-grid">{data.agents.map((agent:any)=><Link href={`/agents/${agent.slug}`} key={agent.slug} className="agent-card"><header><small>{agent.source}</small><LiveStatus label={agent.status}/></header><h3>{agent.name}</h3><div><strong>{agent.value??"—"}</strong><span>{agent.metric}</span></div><footer>View capability <ArrowRight/></footer></Link>)}</div><div className="incident-state-node"><Network/><div><small>SHARED STATE</small><b>Source-attributed incident context</b><p>Updated from the same live API snapshot</p></div></div></section></Page>}

function AgentDetail({slug}:{slug?:string}){const{data,loading,error,reload}=useLiveData("/api/agents");if(loading)return <Page><Loading/></Page>;const agent=data?.agents?.find((item:any)=>item.slug===slug);if(error||!agent)return <Page><Fallback message={error||"This capability is not available in the current agent registry."} reload={reload}/></Page>;return <Page><PageHeading index="04" title={agent.name} subtitle={`Live capability · ${agent.source}`} onRefresh={reload}/><section className="agent-hero"><div><p>CURRENT OUTPUT</p><strong>{agent.value??"—"}</strong><span>{agent.metric}</span></div><div><Metric label="Status" value={agent.status}/><Metric label="Provider" value={agent.source}/></div></section><section className="evidence-layout"><article><h2>How this agent works</h2><p>This capability reads the latest shared snapshot, returns a typed result, and preserves the upstream provider name. When its provider is unavailable, it reports an unavailable state instead of producing a replacement value.</p></article><article><h2>Latest provenance</h2><SourceRow name={agent.source} meta={data.fetchedAt?new Date(data.fetchedAt).toLocaleString():"Freshness unavailable"}/></article></section></Page>}

function Sitrep(){const{data,loading,error,reload}=useLiveData("/api/sitrep");if(loading)return <Page><PageHeading index="05" title="SITREP" subtitle="Generated from the latest live snapshot"/><Loading/></Page>;if(error||!data||data.status==="unavailable")return <Page><PageHeading index="05" title="SITREP" subtitle="Generated from the latest live snapshot"/><Fallback message={error||data?.message} reload={reload}/></Page>;const report=data.reports?.[0];return <Page><PageHeading index="05" title="Situation Report" subtitle="Current source-attributed operational summary" onRefresh={reload}/>{report?<article className="sitrep-document single"><header><div><p>{report.title}</p><h2>{new Date(report.generatedAt).toLocaleString()}</h2></div><Badge tone={tone(report.severity)}>{report.severity}</Badge></header><h3>Executive summary</h3><p>{report.summary}</p><div className="sitrep-metrics"><Metric label="Risk score" value={String(report.risk?.score??"—")}/><Metric label="Severity" value={report.severity}/><Metric label="Live sources" value={String(report.sources.length)}/></div><h3>Provenance</h3><SourceStrip sources={report.sources}/></article>:<Empty title="No report available" copy="The latest data snapshot did not contain enough live information to generate a report."/>}</Page>}

function Ask(){const[query,setQuery]=useState("");const[result,setResult]=useState<any>(null);const[loading,setLoading]=useState(false);async function submit(text:string){setQuery(text);setLoading(true);setResult(null);try{const response=await fetch("/api/ask",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:text})});const json=await response.json();setResult(json)}catch{setResult({message:"Sarathi could not reach the live intelligence service."})}finally{setLoading(false)}}return <Page><PageHeading index="08" title="Ask Sarathi" subtitle="Natural-language access to the current snapshot"/><section className="ask-surface"><p className="kicker">LIVE INTELLIGENCE ASSISTANT</p><h1>What do you need to know?</h1><p>Answers use the current connected API snapshot and list the selected capabilities.</p><form onSubmit={e=>{e.preventDefault();if(query.trim())submit(query)}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ask about current conditions in Chennai…"/><button aria-label="Send" disabled={loading}>{loading?<RefreshCw className="spin"/>:<Send/>}</button></form><div className="suggestions">{["What are current conditions in Chennai?","How much rain is forecast?","What is the current weather risk?"].map(q=><button key={q} onClick={()=>submit(q)}>{q}</button>)}</div>{result&&<div className="answer-panel"><span className="answer-mark">S</span><div><p>{result.answer||result.message}</p>{result.selectedAgents&&<div className="routing-trace"><small>SELECTED CAPABILITIES</small>{result.selectedAgents.map((x:string)=><span key={x}><Check/> {x}</span>)}</div>}{result.sources?.map((source:any)=><SourceRow key={source.name} name={source.name} meta={`${source.authority} · live API`}/>)}</div></div>}</section></Page>}

function Sources(){const{data,loading,error,reload}=useLiveData("/api/sources");if(loading)return <Page><PageHeading index="09" title="Sources" subtitle="Upstream provider health"/><Loading/></Page>;if(error||!data)return <Page><Fallback message={error} reload={reload}/></Page>;return <Page><PageHeading index="09" title="Sources" subtitle="Live upstream provider health" onRefresh={reload}/><Freshness time={data.fetchedAt}/><div className="sources-layout"><section><h2>Connected APIs</h2>{data.sources.map((source:any)=><div className="source-health" key={source.name}><span className={source.status==="live"?"live-dot":"offline-dot"}/><div><b>{source.name}</b><small>{source.authority}</small></div><strong className={source.status}>{source.status.toUpperCase()}</strong><time>{source.fetchedAt?new Date(source.fetchedAt).toLocaleTimeString():"No response"}</time></div>)}</section><section className="source-policy"><ShieldCheck/><h2>Truthful fallback policy</h2><p>Operational values appear only when their upstream API responds. A provider failure is displayed as unavailable and excluded from derived outputs.</p></section></div></Page>}

function System(){const{data,loading,error,reload}=useLiveData("/api/system/status");if(loading)return <Page><PageHeading index="10" title="System" subtitle="Platform and provider health"/><Loading/></Page>;if(error||!data)return <Page><Fallback message={error} reload={reload}/></Page>;return <Page><PageHeading index="10" title="System" subtitle="Platform and provider health" onRefresh={reload}/><Freshness time={data.checkedAt}/><div className="system-grid"><section><h2>Service health</h2>{data.services.map((service:any)=><div className="health-row" key={service.name}><span className={service.status==="live"?"live-dot":"offline-dot"}/><b>{service.name}</b><em className={service.status}>{service.status}</em><strong>{service.authority}</strong></div>)}</section><section className="status-summary"><Gauge/><h2>{data.status}</h2><p>Overall status reflects the live upstream checks shown here.</p></section></div></Page>}

function Page({children}:{children:React.ReactNode}){return <div className="page">{children}</div>}
function Empty({title,copy}:{title:string;copy:string}){return <div className="state-card"><Layers3/><h2>{title}</h2><p>{copy}</p></div>}
function SourceStrip({sources=[]}:{sources:any[]}){return <div className="source-strip">{sources.map(source=><div key={source.name}><span className={source.status==="live"?"live-dot":"offline-dot"}/><b>{source.name}</b><small>{source.status==="live"?"Live API":"Unavailable"}</small></div>)}</div>}
function SourceRow({name,meta}:{name:string;meta:string}){return <div className="source-row"><span className="live-dot"/><div><b>{name}</b><small>{meta}</small></div></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric"><strong>{value}</strong><span>{label}</span></div>}
function LiveStatus({label="LIVE"}:{label?:string}){return <span className={label==="UNAVAILABLE"?"live-status offline":"live-status"}><i/>{label}</span>}
function Badge({children,tone}:{children:React.ReactNode;tone:"red"|"amber"|"green"}){return <span className={`badge ${tone}`}>{children}</span>}
function tone(severity?:string):"red"|"amber"|"green"{return severity==="CRITICAL"||severity==="HIGH"?"red":severity==="MODERATE"?"amber":"green"}
function MapScene(){return <svg className="map-scene" viewBox="0 0 1000 620" preserveAspectRatio="xMidYMid slice" aria-label="Chennai operational map"><defs><pattern id="grid" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M0 18L48 3M8 48L48 28M14 0L0 34" stroke="#24333d" strokeWidth="1" fill="none"/></pattern><radialGradient id="sea" cx="0" cy=".5" r="1"><stop offset="0" stopColor="#0c2b44"/><stop offset="1" stopColor="#06131d"/></radialGradient></defs><rect width="1000" height="620" fill="#0a1014"/><rect width="720" height="620" fill="url(#grid)"/><path d="M720-20C650 110 760 210 700 330S750 490 670 650H1050V-20Z" fill="url(#sea)"/><path d="M720-20C650 110 760 210 700 330S750 490 670 650" fill="none" stroke="#159bd9" strokeWidth="3"/><g stroke="#30434d" fill="none"><path d="M80 570Q260 350 710 170" strokeWidth="7"/><path d="M30 390Q280 300 680 80" strokeWidth="4"/><path d="M120 80Q380 260 690 500" strokeWidth="5"/></g><g fill="#c8d5dc"><text x="455" y="360" fontSize="30">Chennai</text><text x="548" y="145" fontSize="18">Ennore</text><text x="310" y="455" fontSize="18">Ambattur</text><text x="190" y="345" fontSize="18">Avadi</text><text x="725" y="430" fill="#3a8fbd" fontSize="13" letterSpacing="4">BAY OF BENGAL</text></g></svg>}
